#!/usr/bin/env sh

: '
Copyright (c) 2020-present, Martin Novak. All rights reserved.
This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

node "$DIR"/dist/documenter.min.js "$@"